name: Upload updated datasets

on:
  push:
    branches: main

defaults:
  run:
    working-directory: hu_funicular

jobs:
  check-for-changes:
    name: Check for content changes

    runs-on: macos-latest

    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          since_last_remote_commit: true 
          files: hu_funicular/**

  upload-zip:
    name: Package and upload to AWS S3
    
    # needs: [ validate-gtfs ]
    # if: needs.check-for-changes.outputs.any_changed == 'true'
    
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package GTFS
        run: zip gtfs_hu_funicular.zip *

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to AWS S3
        run: |
          aws s3 cp gtfs_hu_funicular.zip s3://gtfs-gy-mate/ \
            --content-disposition attachment
